
import { Layout } from '@/components/layout/Layout';
import { PageHeader } from '@/components/ui/custom/PageHeader';
import { Card, CardContent } from '@/components/ui/card';

const Terms = () => {
  return (
    <Layout>
      <PageHeader 
        title="Terms of Use" 
        subtitle="Legal terms governing the use of our platform"
      />
      
      <div className="container px-4 md:px-6 py-12">
        <Card className="w-full max-w-4xl mx-auto">
          <CardContent className="pt-6">
            <div className="prose prose-sm max-w-none">
              <h2 className="text-xl font-bold mb-4">1. Acceptance of Terms</h2>
              <p className="mb-4">
                By accessing or using the $Gabby AI platform, you agree to be bound by these Terms of Use. If you do not agree to these terms, please do not use our services.
              </p>
              
              <h2 className="text-xl font-bold mb-4">2. Platform Description</h2>
              <p className="mb-4">
                $Gabby is a Web3-native AI platform that enables monetized conversations through blockchain technology. The platform uses the $GABBY token on the BNB Chain for facilitating transactions.
              </p>
              
              <h2 className="text-xl font-bold mb-4">3. User Obligations</h2>
              <p className="mb-4">
                Users agree to:
              </p>
              <ul className="list-disc pl-6 mb-4">
                <li>Provide accurate information when using the platform</li>
                <li>Maintain the security of their wallet and private keys</li>
                <li>Not use the platform for illegal activities or harmful purposes</li>
                <li>Not attempt to manipulate the platform or token economy</li>
                <li>Not share or resell exclusive information obtained through the platform without permission</li>
              </ul>
              
              <h2 className="text-xl font-bold mb-4">4. Token Usage</h2>
              <p className="mb-4">
                The $GABBY token is used for all platform transactions. Users acknowledge that token value may fluctuate and that token transactions are irreversible once confirmed on the blockchain.
              </p>
              
              <h2 className="text-xl font-bold mb-4">5. Content Ownership</h2>
              <p className="mb-4">
                Outputs generated by the AI remain the property of the platform, though users receive a non-exclusive license to use such outputs for personal purposes. Reselling or redistributing AI-generated content may require additional permissions.
              </p>
              
              <h2 className="text-xl font-bold mb-4">6. Limitation of Liability</h2>
              <p className="mb-4">
                $Gabby AI provides its services "as is" without warranties of any kind. We are not liable for any damages arising from your use of the platform, including but not limited to financial losses resulting from token value fluctuations or decisions made based on AI-generated information.
              </p>
              
              <h2 className="text-xl font-bold mb-4">7. Changes to Terms</h2>
              <p className="mb-4">
                We reserve the right to modify these terms at any time. Continued use of the platform after such changes constitutes acceptance of the new terms.
              </p>
              
              <h2 className="text-xl font-bold mb-4">8. Governing Law</h2>
              <p className="mb-4">
                These terms are governed by the laws applicable to the jurisdiction where the platform operates, without regard to conflict of law principles.
              </p>
              
              <p className="mt-8 text-sm text-muted-foreground">
                Last updated: May 2025
              </p>
            </div>
          </CardContent>
        </Card>
      </div>
    </Layout>
  );
};

export default Terms;
